name: Process Issue Number

on:
  workflow_dispatch:

jobs:
  process-issue:
    runs-on: ubuntu-latest
    steps:
      - name: List files in current workspace before downloading
        run: |
          echo "Listing files in workspace before downloading artifact:"
          ls -alh ./artifacts  # This lists all files in the current directory

      - name: Download Issue Number Artifact
        uses: actions/download-artifact@v3
        with:
          name: issue-number  # Ensure this matches the artifact name from Workflow 1
          path: ./artifacts # Store the downloaded artifact in the current directory

      - name: List files after downloading
        run: |
          echo "Listing files after downloading the artifact:"
          ls -alh  # Check if issue_number.txt is in the directory

      - name: Read Issue Number
        run: |
          ISSUE_NUMBER=$(cat issue_number.txt)
          echo "Processing issue number: $ISSUE_NUMBER"

      - name: Example Processing Step
        run: |
          ISSUE_NUMBER=$(cat issue_number.txt)
          # Perform your processing logic here
          echo "Processing logic with issue #$ISSUE_NUMBER"
