name: Print GitHub Secrets

on:
  push:
    branches:
      - main

jobs:
  print-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print credentials
      run: |
        echo "API Key: $API_KEY"
        echo "DB Password: $DB_PASSWORD"
      env:
        API_KEY: ${{ secrets.API_KEY }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
