name: Update RAN_SECRET

on:
  workflow_dispatch:

jobs:
  update-secret:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write  # This grants write permission to update secret
    steps:
      - name: Install necessary tools
        run: |
          sudo apt-get update
          sudo apt-get install jq python3 python3-pip

      - name: Install PyNaCl (Python bindings for LibSodium)
        run: pip3 install pynacl

      - name: Generate random value for the secret
        id: generate-secret
        run: echo "secret=$(openssl rand -base64 32)" >> $GITHUB_ENV

      - name: Get public key for encryption
        id: get-public-key
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/gowrisankar22/testworkflow/actions/secrets/public-key \
            -o public_key.json

          key=$(jq -r '.key' public_key.json)
          key_id=$(jq -r '.key_id' public_key.json)
          echo "key=$key" >> $GITHUB_ENV
          echo "key_id=$key_id" >> $GITHUB_ENV

      - name: Encrypt the secret using Python and LibSodium
        id: encrypt-secret
        run: |
          echo "
          import base64
          from nacl import encoding, public
          
          # Read public key and secret
          public_key = base64.b64decode('${{ env.key }}')
          secret = '${{ env.secret }}'.encode('utf-8')
          
          # Encrypt the secret using LibSodium
          sealed_box = public.SealedBox(public.PublicKey(public_key))
          encrypted = sealed_box.encrypt(secret)
          
          # Base64 encode the encrypted value for GitHub API
          encrypted_value = base64.b64encode(encrypted).decode('utf-8')
          print(f'encrypted_value={encrypted_value}')
          " > encrypt.py

          encrypted_value=$(python3 encrypt.py)
          echo "encrypted_value=$encrypted_value" >> $GITHUB_ENV

      - name: Update RAN_SECRET in GitHub Secrets
        run: |
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/gowrisankar22/testworkflow/actions/secrets/RAN_SECRET \
            -d "{\"encrypted_value\":\"${{ env.encrypted_value }}\", \"key_id\":\"${{ env.key_id }}\"}"
