name: Rotate and Print RAN_SECRET

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  rotate-secret:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: write  # This grants write permission to update secrets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate new secret
        id: generate-secret
        run: |
          # Generate a new random 64-character hexadecimal secret
          NEW_SECRET=$(openssl rand -hex 32)
          echo "New secret generated: $NEW_SECRET"
          echo "NEW_SECRET=${NEW_SECRET}" >> $GITHUB_ENV

      - name: Update GitHub secret
        run: |
          # Use GitHub's REST API to update the secret RAN_SECRET in the repository
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/RAN_SECRET \
            -d "{\"encrypted_value\":\"${NEW_SECRET}\"}"

      - name: Base64 encode the secret
        run: |
          echo "Base64 encoded secret: $(echo -n '${{ env.NEW_SECRET }}' | base64)"
      
      - name: Decode and print the secret
        run: |
          # Print the new secret after decoding it
          echo "The new secret (decoded) is: $(echo -n '${{ env.NEW_SECRET }}' | base64 --decode)"
