name: Update RAN_SECRET

on:
  workflow_dispatch:

jobs:
  update-secret:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write  # This grants write permission to update secret
    steps:
      - name: Install necessary tools
        run: |
          sudo apt-get update
          sudo apt-get install libsodium-dev jq curl

      - name: Generate random value for the secret
        id: generate-secret
        run: echo "secret=$(openssl rand -base64 32)" >> $GITHUB_ENV

      - name: Get public key for encryption
        id: get-public-key
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/gowrisankar22/testworkflow/actions/secrets/public-key \
            -o public_key.json

          key=$(jq -r '.key' public_key.json)
          key_id=$(jq -r '.key_id' public_key.json)
          echo "key=$key" >> $GITHUB_ENV
          echo "key_id=$key_id" >> $GITHUB_ENV

      - name: Encrypt the secret using LibSodium
        id: encrypt-secret
        run: |
          secret_bytes=$(echo -n "${{ env.secret }}" | base64 -d | xxd -p -c 256)
          pub_key_hex=$(echo -n "${{ env.key }}" | base64 -d | xxd -p -c 256)

          # Use LibSodium to encrypt the secret
          encrypted_value=$(echo "$secret_bytes" | sodium-native sodium-box-seal --key "$pub_key_hex")

          # Base64 encode the encrypted value for the API call
          echo "encrypted_value=$(echo -n $encrypted_value | base64)" >> $GITHUB_ENV

      - name: Update RAN_SECRET in GitHub Secrets
        run: |
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/gowrisankar22/testworkflow/actions/secrets/RAN_SECRET \
            -d '{"encrypted_value":"${{ env.encrypted_value }}", "key_id":"${{ env.key_id }}"}'
       
